language: python
python:
  - "3.10"

services:
  - sqlite

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - pytest