# Generated by Django 4.2.21 on 2025-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_description_alter_ad_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
